-- Simple signup abuse protection: cap new accounts from the same IP address.
-- After applying this migration, enable `public.hook_limit_signup_by_ip` as the
-- Supabase Auth "Before User Created" hook in the dashboard.

create table if not exists public.signup_ip_events (
  id bigint generated by default as identity primary key,
  ip_address inet not null,
  user_id uuid,
  provider text,
  created_at timestamptz not null default now()
);

create index if not exists signup_ip_events_ip_created_idx
  on public.signup_ip_events (ip_address, created_at desc);

grant usage on schema public to supabase_auth_admin;
revoke all on table public.signup_ip_events from anon, authenticated, public;
grant select, insert on table public.signup_ip_events to supabase_auth_admin;
grant usage, select on sequence public.signup_ip_events_id_seq to supabase_auth_admin;

create or replace function public.hook_limit_signup_by_ip(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ip inet;
  v_user_id uuid;
  v_provider text;
  v_recent_count int;
  v_daily_limit int := 3;
begin
  v_ip := nullif(event->'metadata'->>'ip_address', '')::inet;
  v_user_id := nullif(event->'user'->>'id', '')::uuid;
  v_provider := nullif(event->'user'->'app_metadata'->>'provider', '');

  if v_ip is null then
    return '{}'::jsonb;
  end if;

  insert into public.signup_ip_events (ip_address, user_id, provider)
  values (v_ip, v_user_id, v_provider);

  select count(*) into v_recent_count
  from public.signup_ip_events
  where ip_address = v_ip
    and created_at >= now() - interval '24 hours';

  if v_recent_count > v_daily_limit then
    return jsonb_build_object(
      'error', jsonb_build_object(
        'message', 'We could not create an account from this network right now.',
        'http_code', 429
      )
    );
  end if;

  return '{}'::jsonb;
end;
$$;

grant execute on function public.hook_limit_signup_by_ip(jsonb) to supabase_auth_admin;
revoke execute on function public.hook_limit_signup_by_ip(jsonb) from anon, authenticated, public;
