-- Migration 33 — a durable brake on MetaApi account CREATES.
--
-- Apply on the production database (Supabase SQL editor). Idempotent; safe to re-run.
-- Depends on migration_27_broker_sync.sql.
--
-- Creating an account at MetaApi costs $2.10 up front and bills from then on. The only brake
-- on that today is the credential-attempt limiter, whose counter lives in the Node module
-- memory of ONE serverless instance: a loop that spreads across cold starts sees a fresh
-- budget every time. That limiter is sized for the $0.105 credential validation, where the
-- leak is a nuisance; at $2.10 a go it is a bill.
--
-- One row per create ATTEMPT, counted over a rolling day. The row is written BEFORE MetaApi is
-- called, because the money is spent the moment MetaApi accepts: an attempt that is then killed
-- mid-flight, or that exhausts its 202 polling, is the case that leaves a paid account nobody
-- points at — exactly the one a brake must not be blind to. An attempt MetaApi refuses on
-- validation creates nothing, and the route deletes its row again (see refundBrokerCreate).
--
-- Three a day is the legitimate ceiling: switching broker twice in one day, with a mistake in
-- between. Traders never see it; loops do.
--
-- `id` exists only so that refund can name the row it just wrote. Nothing else reads a single
-- row — every other query counts a user's rows over a window, which the index below serves.
create table if not exists public.broker_create_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists broker_create_events_user_created_idx
  on public.broker_create_events (user_id, created_at desc);

alter table public.broker_create_events enable row level security;

-- No policies at all: the route writes and counts with the service role, and there is nothing
-- here a trader needs to read. Same trust model as broker_accounts' writes.

-- Housekeeping is deliberately manual. Rows older than a day are dead weight, but the table
-- grows by a handful of rows per connecting trader per day — years of it is still small, and a
-- pg_cron job to delete them would cost more attention than the disk does. Prune with:
--   delete from public.broker_create_events where created_at < now() - interval '30 days';
