export const ASK_HISTORY_PAGE_SIZE = 20;
export const ASK_MODEL_HISTORY_LIMIT = 8;
export const ASK_CLIENT_CONTEXT_WINDOW_SIZE = ASK_MODEL_HISTORY_LIMIT;
export const ASK_ATTACHMENT_MAX_BYTES = 5 * 1024 * 1024;
export const ASK_ATTACHMENTS_BUCKET = "ask-attachments";
export const ASK_ATTACHMENT_SIGNED_URL_TTL_SECONDS = 60 * 60 * 24;
