import type { Block } from "@/lib/blog/posts";

/**
 * Additional depth for each post, spliced in before the post's final section by `posts.ts`.
 * General and evergreen. No claims about named firms.
 */
export const EXTRA: Record<string, Block[]> = {
  "how-to-check-if-a-broker-is-fca-regulated": [
    { type: "h2", text: "Reading the register entry properly" },
    { type: "p", text: "A register entry has several parts and each answers a different question. The status says whether the firm is authorised today. The permissions section lists the regulated activities it may carry on. The contact details show the address, phone number and website the regulator has on file. The individuals and appointed representatives sections show who works for the firm and which other firms act under its authority." },
    { type: "ul", items: [
      "Status: look for authorised, and read the date. A status such as cancelled or in run-off means the firm should not be taking new business.",
      "Permissions: a firm that arranges deals in investments is not automatically allowed to deal as principal or to hold client money. Match the permissions to what you are being offered.",
      "Requirements and limitations: some firms are authorised with conditions attached, such as not being allowed to hold client money. These notes matter.",
      "Trading names: a brand you know may not be the legal firm at all. Check whether the trading name appears against the firm reference number you were given.",
    ] },
    { type: "h2", text: "A worked example of a mismatch" },
    { type: "p", text: "Suppose a website says it is authorised and shows a reference number. You search the number and it belongs to a genuine authorised firm, but the firm is a small advisory business with a different name, a different address and a different website. Nothing about that entry supports the trading platform you are looking at. This is what a clone or misuse of a reference number looks like, and it is why matching the details, not just finding the number, is the step that matters." },
    { type: "h2", text: "What to do if you cannot find the firm" },
    { type: "ol", items: [
      "Ask the firm for its full legal name and reference number in writing. A regulated firm can answer this immediately.",
      "Search the register by the legal name as well as by the number, in case of a typo.",
      "Check the FCA Warning List and any similar list from the regulator in the firm's stated country.",
      "Contact the regulator through the contact details on its own website, not the ones supplied by the firm, and ask whether the firm is authorised.",
      "Until you have a verifiable answer, do not deposit.",
    ] },
    { type: "p", text: "Doing this once for each new broker takes a few minutes. It is worth repeating if a broker later asks you to move to a different entity or a different platform, because that is exactly when protections can change without much notice." },
  ],

  "prop-firm-challenge-rules-that-catch-traders-out": [
    { type: "h2", text: "How to read a firm's rule page" },
    { type: "p", text: "Rule pages are written to be short and marketing pages are written to be attractive, so the two can differ. The rule text, together with any terms and conditions or FAQ it links to, is what actually governs your account. Print or save the version you accepted, because rules can be updated and disputes are decided on the wording, not on what you remember." },
    { type: "h2", text: "Definitions that decide breaches" },
    { type: "ul", items: [
      "Reference balance: is a daily limit measured from the start-of-day balance, the start-of-day equity or the initial account size? The same loss can be inside one definition and outside another.",
      "Balance or equity: rules measured on equity count floating losses on open trades, so a deep open drawdown can trigger a breach before you close anything.",
      "Reset time: the trading day ends at a set time, often tied to a particular time zone. A trade that straddles it can count towards two days.",
      "Static or trailing: a static maximum drawdown stays put while a trailing one follows your highest point. Some trailing limits stop trailing once a threshold is reached.",
      "What counts as a trading day: some firms require a minimum number of days with a trade of a minimum size.",
    ] },
    { type: "h2", text: "Rules people forget until they matter" },
    { type: "ul", items: [
      "News restrictions: which events count, and how long before and after they apply.",
      "Weekend and overnight holding: some accounts must be flat before the weekend.",
      "Prohibited strategies: for example martingale-style sizing, latency tricks, or copying other accounts, depending on the firm.",
      "Consistency conditions: limits on how much of your profit may come from one day or one trade.",
      "Inactivity: an account can be closed if it does not trade for a set period.",
      "Payout conditions: minimum days between payouts, minimum profit before withdrawal and any verification steps.",
    ] },
    { type: "h2", text: "A pre-payment checklist" },
    { type: "ol", items: [
      "Confirm the firm is operating and read what independent records say about it.",
      "Read the current rules in full and note every definition above.",
      "Work out the risk per trade that keeps a normal losing streak inside the daily limit.",
      "Check the news rule against a calendar for the coming weeks.",
      "Understand exactly what happens to fees and to profit if a rule is breached.",
    ] },
    { type: "p", text: "A challenge fee is money at risk. Treating the rules as a contract, and reading them before payment rather than after a breach, is the cheapest protection you have." },
  ],

  "position-sizing-how-much-to-risk-per-trade": [
    { type: "h2", text: "Sizing with different account currencies" },
    { type: "p", text: "The pip value in the formula is measured in your account currency. If you trade EUR/USD from a dollar account, a standard lot is worth 10 dollars per pip. From a pound account that pip has to be converted into pounds at the current GBP/USD rate, so the same lot is worth less than 10 pounds per pip when the pound is stronger than the dollar. For pairs where your own currency is the base, such as USD/JPY on a dollar account, the conversion uses the pair's own price." },
    { type: "p", text: "The easiest way to avoid mistakes is to use a calculator that asks for your account currency and any rate it needs, rather than assuming 10 for every pair." },
    { type: "h2", text: "A second worked example" },
    { type: "ul", items: [
      "Account 5,000, risk 0.5% = 25 at risk.",
      "GBP/USD long with a 15 pip stop, USD account, pip value 10 per standard lot.",
      "Lots = 25 / (15 x 10) = 0.1667, which rounds down to 0.16 lots on a broker with a 0.01 step.",
      "Rounding down keeps the risk at or below the 25 you planned. Rounding up would exceed it.",
    ] },
    { type: "h2", text: "Sizing when the stop changes" },
    { type: "p", text: "If price moves in your favour and you move the stop to break even, the size does not change. If you add to a winning position, calculate the total risk of both positions from the new stop, not each piece separately. If you widen a stop after entry because you do not want to be stopped out, you have increased the risk beyond the plan, which is the most common way sizing rules are broken in practice." },
    { type: "h2", text: "Checking risk across several trades" },
    { type: "ul", items: [
      "Add up the risk of all open trades. Five trades each risking 1% is a 5% exposure if they all lose together.",
      "Look for shared drivers. Long EUR/USD, long GBP/USD and short USD/CHF are three ways of betting against the dollar.",
      "Set a cap on total open risk, as well as risk per trade, and keep to it.",
      "Around scheduled news, correlated positions tend to move together, so the cap matters most then.",
    ] },
    { type: "p", text: "Sizing is not exciting, and it is the part of trading that most reliably separates accounts that survive a bad run from accounts that do not." },
  ],

  "how-to-tell-a-scam-broker-from-a-real-one": [
    { type: "h2", text: "How the typical scam unfolds" },
    { type: "p", text: "Most of these schemes follow a pattern. First contact comes through social media, a messaging app or a call from someone offering to help you trade. A small first deposit appears to grow quickly on a platform that looks professional, and the platform may show profits that are numbers on a screen rather than a market. You are encouraged to deposit more, and often to take a bonus. When you try to withdraw, new conditions appear: taxes, fees, verification steps or minimum trading volumes. Eventually contact stops or you are asked for more money to release what is already yours." },
    { type: "h2", text: "Questions worth asking any broker" },
    { type: "ul", items: [
      "What is the exact legal name of the company that will hold my account, and where is it registered?",
      "Which regulator authorises it, and what is the licence number?",
      "Where is client money held, and is it kept separate from company funds?",
      "Which compensation scheme, if any, covers my account?",
      "What are the fees for deposits, withdrawals, inactivity and currency conversion?",
      "How long do withdrawals take, and what checks apply?",
    ] },
    { type: "p", text: "A genuine broker answers these without hesitation and in writing. Vague answers, pressure, or a refusal to give a licence number are all reasons to walk away." },
    { type: "h2", text: "Demo accounts are not proof" },
    { type: "p", text: "A demo account or a platform screenshot showing profits proves nothing about whether you can withdraw real money. The test is what happens with a small real deposit and a small real withdrawal, and even that is not conclusive on its own, because some schemes allow small withdrawals to build trust before a large deposit." },
    { type: "h2", text: "Get help early" },
    { type: "p", text: "The sooner you act, the better the chance of a route to recover money. If you are unsure about a broker, ask the regulator directly through its own website, and talk to your bank if you have already sent funds. Be wary of anyone who contacts you offering to recover lost money for an upfront fee: that is a common follow-up scam." },
  ],

  "fscs-cysec-and-client-money-protection-explained": [
    { type: "h2", text: "A worked example" },
    { type: "p", text: "Suppose a UK-authorised broker fails and cannot return client assets. Its client money was segregated, so the administrators first try to return that money to clients. If there is a shortfall, an eligible client may be able to claim from the FSCS, subject to the limit and the scheme's rules. Now suppose the same brand also runs an offshore entity, and your account was opened there. The UK compensation scheme would not be the relevant route, because the contract is with a different company under a different regulator, if it is regulated at all." },
    { type: "h2", text: "Questions to ask about protection" },
    { type: "ul", items: [
      "Which legal entity holds my account, and which regulator authorises it?",
      "Is my money segregated, and with which bank?",
      "Does a compensation scheme cover this entity, and what is its limit?",
      "Do I qualify as a retail client? A professional classification can remove protections.",
      "Does negative balance protection apply to my account?",
    ] },
    { type: "h2", text: "Professional client status" },
    { type: "p", text: "Some brokers offer to reclassify retail clients as professional in exchange for higher leverage or other terms. Professional clients give up certain retail protections, which can include compensation scheme coverage and negative balance protection in some regimes. The eligibility tests exist for a reason, and giving up protection is a decision to make deliberately, with the trade-offs clear." },
    { type: "h2", text: "Protection and risk are different things" },
    { type: "p", text: "It is easy to read a compensation scheme as a safety net for losses. It is narrower than that: it addresses the failure of an authorised firm, not the outcome of your trades. The controls that protect you from trading losses are your own: position size, stop placement and drawdown limits." },
  ],

  "what-is-drawdown-and-how-to-manage-it": [
    { type: "h2", text: "Drawdown in a losing streak" },
    { type: "p", text: "Even a strategy with a positive edge produces losing streaks, and the length of a streak depends on the win rate. A strategy that wins half its trades will, over a few hundred trades, very likely have a run of six or more losses in a row at some point. If each loss costs 2% of the account, six in a row is roughly an 11.4% drawdown, because each loss is taken from a smaller balance." },
    { type: "ul", items: [
      "At 1% risk per trade, six losses in a row cost about 5.9%.",
      "At 2% risk, about 11.4%.",
      "At 5% risk, about 26.5%.",
      "At 10% risk, about 46.9%.",
    ] },
    { type: "p", text: "These figures show why a risk per trade that feels acceptable on one trade can be unacceptable across a streak. Decide your risk per trade by asking what a bad run would do to the account, not what one loss would do." },
    { type: "h2", text: "Drawdown and prop firm limits" },
    { type: "p", text: "A daily loss limit that is small compared with your normal trading range is easy to hit by accident. If your risk per trade is 1% and a firm's daily limit is 5%, five losing trades in a day breach it, and slippage or a wide spread can make it fewer. Work backwards from the limit to a risk per trade and a daily stop that leave a comfortable margin." },
    { type: "h2", text: "What to do when you are in a drawdown" },
    { type: "ol", items: [
      "Check whether you are following your plan. A drawdown from correct execution is different from one caused by rule breaks.",
      "Reduce size until you have a run of trades that follow the rules.",
      "Review the losses in your journal for a pattern such as time of day, pair or setup.",
      "Do not try to recover it in one trade. Recovery is a matter of returning to normal size and normal process.",
      "Consider a pause if you are trading emotionally.",
    ] },
    { type: "p", text: "A drawdown is information as much as damage. What matters is whether it came from the strategy behaving as its statistics suggested, or from you departing from the strategy." },
  ],

  "risk-reward-and-win-rate-what-the-maths-says": [
    { type: "h2", text: "Three example strategies" },
    { type: "ul", items: [
      "Strategy A wins 35% of trades, with an average win of 3R and an average loss of 1R. Expectancy per trade is (0.35 x 3) minus (0.65 x 1) = 0.40R.",
      "Strategy B wins 60% of trades, with an average win of 1R and an average loss of 1R. Expectancy is (0.6 x 1) minus (0.4 x 1) = 0.20R.",
      "Strategy C wins 70% of trades, with an average win of 0.5R and an average loss of 1.5R. Expectancy is (0.7 x 0.5) minus (0.3 x 1.5) = -0.10R, a losing strategy despite the high win rate.",
    ] },
    { type: "p", text: "Here R means the amount risked on a trade. Measuring results in R makes strategies comparable regardless of account size. Notice that the strategy with the lowest win rate has the best expectancy, and the one with the highest loses money. That is the point of looking at both numbers together." },
    { type: "h2", text: "What costs do to the numbers" },
    { type: "p", text: "Suppose the spread and commission on a trade cost 0.1R. Strategy A's expectancy drops from 0.40R to 0.30R, Strategy B's from 0.20R to 0.10R, and Strategy C's from -0.10R to -0.20R. Strategy B has lost half its edge. Costs scale with how often you trade and how tight your stops are, so high-frequency, tight-stop approaches are the most exposed." },
    { type: "h2", text: "Sample size and honesty" },
    { type: "p", text: "A win rate calculated from 20 trades is very noisy. Fifty trades tell you a little more, and a few hundred a lot more, provided the market conditions were varied. Journal every trade, including the ones you would rather forget, and resist choosing which trades to count. A results table that leaves out the bad days is not measuring your strategy." },
    { type: "h2", text: "Turning it into a rule" },
    { type: "ol", items: [
      "Define your setup precisely enough that two people would agree whether a trade qualifies.",
      "Record every trade of that setup in R, including costs.",
      "Review expectancy after a meaningful sample, and reduce size if it turns negative.",
      "Only change one variable at a time, so you know what moved the result.",
    ] },
  ],

  "how-to-keep-a-trading-journal": [
    { type: "h2", text: "A simple template" },
    { type: "ul", items: [
      "Before the session: the plan in two lines. What am I looking for, and what would make me stop for the day?",
      "Each trade: instrument, direction, size, entry, stop, target, result in money and in R, and a one-line reason for the entry.",
      "After the session: did I follow the plan (yes, partly, no), how did I feel, and what is the one thing to repeat or stop?",
      "Weekly: the three numbers that matter to you, such as win rate, average R and largest drawdown, plus the most common rule break.",
    ] },
    { type: "h2", text: "Screenshots and notes" },
    { type: "p", text: "A chart screenshot at entry, and another at exit, captures what you saw at the time and prevents hindsight from rewriting it. Keep the notes short and factual: what you saw, what you did and what happened. Save the analysis for the review." },
    { type: "h2", text: "Tags that pay off" },
    { type: "ul", items: [
      "Setup type, so you can compare performance by setup.",
      "Session or time of day.",
      "Rule followed or broken, and which rule.",
      "Emotional state: calm, rushed, frustrated, bored, overconfident.",
      "News day or not.",
    ] },
    { type: "p", text: "After a month of tagged entries you can ask concrete questions. Do I lose more on news days? Is my second trade of the day worse than my first? Do I break rules more when I slept badly? Each answer suggests a specific rule to add." },
    { type: "h2", text: "Common ways journals fail" },
    { type: "ul", items: [
      "Recording only the trades and not the reasoning, so you cannot tell luck from skill.",
      "Recording only the good days.",
      "Writing pages of narrative that you never reread.",
      "Reviewing too rarely, so patterns pass unnoticed, or too often, so noise looks like signal.",
      "Treating the journal as a judgement rather than a record.",
    ] },
    { type: "p", text: "Automation helps here: if trades are imported from your broker, the mechanical part is done and you only need to add your reasoning and mood, which is the part nobody else can record for you." },
  ],

  "revenge-trading-and-tilt-how-to-stop": [
    { type: "h2", text: "A realistic scenario" },
    { type: "p", text: "You risk 1% on a setup you like and are stopped out. Price then reverses and would have hit your target. The loss feels unfair, so you re-enter immediately with double the size, with no fresh setup, to make it back. That trade also loses, and now you are 3% down on the day, well past a limit you would normally respect. The next trade is bigger again. Nothing about the market changed. What changed is that the trade stopped being an execution of a plan and became an attempt to undo a loss." },
    { type: "h2", text: "Physical and mental warning signs" },
    { type: "ul", items: [
      "A faster heart rate, tense shoulders or shallow breathing after a loss.",
      "Inner talk such as I need to get this back, or I will not finish the day red.",
      "Watching every tick and refreshing the chart repeatedly.",
      "Skipping the checks you normally run before entering.",
      "Justifying a trade with reasons you would not accept in a calm moment.",
    ] },
    { type: "h2", text: "Building a circuit breaker" },
    { type: "ol", items: [
      "Write the rule down: for example, two losses in a row, or a 2% daily loss, means I stop and close the platform.",
      "Make it physical. Stand up, leave the desk, and go outside for a set time.",
      "Set an alert or a timer, so the break starts automatically.",
      "Tell someone or keep a visible checklist, so the rule does not depend on your mood.",
      "After the break, write two lines on what happened before you consider trading again.",
    ] },
    { type: "h2", text: "Fixing the conditions, not just the moment" },
    { type: "p", text: "Revenge trading is more likely when you are tired, stressed, trading money you cannot afford to lose, or working against a hard limit. Trade smaller if pressure is high. Keep risk per trade small enough that a single loss does not sting. Look at sleep, workload and finances as inputs to your trading, because they show up in your results." },
    { type: "h2", text: "When to get help" },
    { type: "p", text: "If trading is causing you sustained anxiety, if you cannot stop despite harm, or if it is affecting your relationships or finances, talk to a qualified professional or a support organisation. Self-help tools and journals are useful for habits, and they are not a substitute for professional support." },
  ],

  "how-to-trade-around-economic-news": [
    { type: "h2", text: "A worked example of the spread effect" },
    { type: "p", text: "A pair that normally trades with a spread of one pip can widen to several pips in the moments around a major release. If you had a stop 10 pips from your entry and the spread widens to 5 pips, a spike can trigger the stop even though the underlying price barely moved against you. This is why some traders widen stops or reduce size before news, and why tight-stop strategies are the most exposed." },
    { type: "h2", text: "Building news into your plan" },
    { type: "ol", items: [
      "Mark the high-impact events for your instruments on your weekly plan.",
      "Decide the rule for each: flat before, half size, or trade the reaction.",
      "Set a buffer, for example no new entries within 15 minutes before an event, and follow it.",
      "After the release, wait for the spread to normalise before you reassess.",
      "Record the outcome in your journal so you learn how your instruments behave.",
    ] },
    { type: "h2", text: "Central bank events deserve extra care" },
    { type: "p", text: "Interest rate decisions often come with a statement and a press conference. The initial reaction can reverse when the press conference begins, so the volatile period can last longer than a single release. Treat the whole window as high-risk unless you have a plan for it." },
    { type: "h2", text: "Time zones and daylight saving" },
    { type: "p", text: "Two mistakes are common: using a calendar set to the wrong time zone, and forgetting that daylight saving shifts on different dates in different countries, so a release can move by an hour relative to your local time for a few weeks a year. Check the calendar's time zone setting whenever the clocks change." },
    { type: "h2", text: "Beyond scheduled data" },
    { type: "p", text: "Not all news is scheduled. Central bank speakers, geopolitical events and company news can move markets without warning. A calendar helps with the scheduled part. For the rest, sensible position sizing and stops you can live with are the only protection." },
  ],
};

/** A short recap appended to the end of each post. */
export const TAKEAWAYS: Record<string, string[]> = {
  "how-to-check-if-a-broker-is-fca-regulated": [
    "Search the FCA Register by firm reference number, not brand name.",
    "Check status, permissions and any requirements, and match address, website and phone to what you were given.",
    "Search the FCA Warning List for the brand and the web address.",
    "Confirm you are being onboarded to the UK-authorised entity, not an offshore sibling.",
    "If you cannot verify the firm, do not deposit.",
  ],
  "prop-firm-challenge-rules-that-catch-traders-out": [
    "The rule text and terms govern your account, not the marketing page.",
    "Definitions decide breaches: reference balance, balance or equity, reset time and trailing or static.",
    "Read the news, weekend, prohibited strategy, consistency and payout rules before you pay.",
    "Work backwards from the daily limit to a risk per trade with room for slippage.",
    "Save the version of the rules you accepted.",
  ],
  "position-sizing-how-much-to-risk-per-trade": [
    "Lots = risk amount / (stop in pips x pip value per lot).",
    "Set the stop from the chart, then let the size follow.",
    "Round lot size down to your broker's step, never up.",
    "Add up the risk of correlated open trades, and cap total open risk.",
    "Never widen a stop after entry to avoid a loss.",
  ],
  "how-to-tell-a-scam-broker-from-a-real-one": [
    "Unsolicited contact, guaranteed returns and deposit pressure are warning signs on their own.",
    "Verify the legal entity and licence on the regulator's own register and compare contact details.",
    "A demo account or on-screen profit proves nothing about withdrawals.",
    "Stop sending money and act quickly if you suspect a scam.",
    "Be wary of anyone offering to recover lost money for a fee.",
  ],
  "fscs-cysec-and-client-money-protection-explained": [
    "Protection follows the legal entity that holds your account, not the brand.",
    "Segregation, compensation schemes and negative balance protection are three separate safeguards.",
    "Compensation covers the failure of an authorised firm, not trading losses.",
    "Check the current limits on the scheme's own website.",
    "Professional client status can remove retail protections.",
  ],
  "what-is-drawdown-and-how-to-manage-it": [
    "Drawdown is the fall from a peak to a later low.",
    "Recovery needs a bigger percentage gain than the loss.",
    "Choose risk per trade by asking what a losing streak would do, not one loss.",
    "Check whether a rule uses balance or equity, and how it resets.",
    "Reduce size in a drawdown and review the cause before you try to recover.",
  ],
  "risk-reward-and-win-rate-what-the-maths-says": [
    "Break-even win rate = 1 / (1 + reward to risk), before costs.",
    "Expectancy combines win rate with average win and loss.",
    "Measure results in R so strategies compare fairly.",
    "Costs cut deepest into tight-stop, high-frequency approaches.",
    "Small samples mislead, so record every trade.",
  ],
  "how-to-keep-a-trading-journal": [
    "Keep the daily entry to about a minute: result, plan followed, mood, one lesson.",
    "Import trades where you can, so you only write the human part.",
    "Review weekly for patterns and monthly for numbers.",
    "Tag setups, sessions, rule breaks and emotional state.",
    "Record the bad days, and treat the journal as data, not judgement.",
  ],
  "revenge-trading-and-tilt-how-to-stop": [
    "Revenge trading is trading to undo a loss, not to follow a plan.",
    "Set a written circuit breaker: consecutive losses or a daily loss means stop.",
    "Keep size fixed after a loss and cap trades per day.",
    "Fix the conditions: sleep, stress, money you cannot afford to lose.",
    "Seek professional support if trading is harming your wellbeing.",
  ],
  "how-to-trade-around-economic-news": [
    "Scheduled releases are predictable in time, not in outcome.",
    "Spreads widen and stops can slip around high-impact events.",
    "Decide in advance: stay flat, reduce size, or trade it deliberately.",
    "Check the calendar's time zone, especially around daylight saving changes.",
    "Read your prop firm's exact news rule and do not rely on summaries.",
  ],
};
