import type { BlogPost } from "@/lib/blog/posts";

/**
 * Topic-cluster posts: broker safety, prop firm rules, risk maths, psychology, news.
 * General and evergreen. No claims about named firms. Regulatory figures must be re-checked
 * at each review. Client review required before launch.
 */
export const MORE_POSTS: BlogPost[] = [
  {
    slug: "how-to-tell-a-scam-broker-from-a-real-one",
    title: "How to tell a scam broker from a real one",
    description:
      "Warning signs of a scam broker or clone firm, a checklist you can run in ten minutes, and what to do if you have already sent money to one.",
    date: "2026-09-29",
    category: "Broker safety",
    relatedPosts: ["how-to-check-if-a-broker-is-fca-regulated", "fscs-cysec-and-client-money-protection-explained"],
    terms: ["clone-firm", "warning-list", "regulated-broker", "negative-balance-protection"],
    related: [
      { href: "/verify", label: "Verify a broker" },
      { href: "/compare/brokers", label: "Compare brokers" },
      { href: "/glossary/clone-firm", label: "What is a clone firm?" },
    ],
    body: [
      { type: "p", text: "Most losses to bad brokers are not caused by trading. They happen before the first trade: a deposit goes in and either the money cannot come out, or the platform was never a real market at all. The good news is that the warning signs are consistent, and a short checklist catches most of them." },
      { type: "h2", text: "The warning signs" },
      {
        type: "ul",
        items: [
          "Unsolicited contact. A message, call or social media approach offering a trading opportunity is the most common way people are recruited. Legitimate brokers do not cold-call retail clients with guaranteed returns.",
          "Promised or guaranteed returns. No one can guarantee profit in trading. Any figure quoted as a certain monthly or weekly return is a red flag on its own.",
          "Pressure to deposit quickly. Countdown offers, bonuses that expire today and a personal account manager pushing you to add more money are sales tactics, not services.",
          "No licence number, or one you cannot verify. A genuine regulated firm publishes its authorisation details and they match the regulator's register.",
          "A bonus that locks your withdrawals. Some offers make you trade a huge volume before you can withdraw anything.",
          "Withdrawal friction. New fees, extra identity checks that never end, or sudden account restrictions when you ask for your money back.",
          "Payment to a third party. If you are asked to send money to a personal account, an unrelated company or a crypto wallet, stop.",
        ],
      },
      { type: "h2", text: "A ten-minute check" },
      {
        type: "ol",
        items: [
          "Get the exact legal name of the company that will hold your account, and the licence or reference number, from the terms and conditions.",
          "Look that number up on the regulator's own register, not through a link the broker supplied. For UK firms that is the FCA Register.",
          "Compare the registered address, website and phone number on the register with the ones you were given. A mismatch is the signature of a clone firm.",
          "Search the regulator's warning list for the brand name and the website address. Many regulators, including the FCA, publish these.",
          "Check the permissions. A firm can be authorised for some activities and not for the one you are using it for.",
          "Read the terms for withdrawals, bonuses and inactivity fees before you deposit anything.",
        ],
      },
      { type: "callout", text: "Absence from a warning list does not prove a firm is genuine. New scams appear faster than lists are updated, so a clean search is one input, not a clearance." },
      { type: "h2", text: "Clone firms and why they work" },
      { type: "p", text: "A clone firm copies the name and sometimes the firm reference number of a real authorised firm, then builds a convincing website with different contact details. If you only check that the number exists on the register, a clone passes. That is why the contact details on the register are the ones to trust, and why you should always compare them with what you were given." },
      { type: "h2", text: "Regulated does not mean risk-free" },
      { type: "p", text: "Even a genuinely regulated broker can be a poor fit. Regulators differ in how strictly they supervise, and one broker group can run several entities under different regulators. The entity that holds your account decides which rules and which compensation schemes apply, so confirm you are being onboarded to the entity you checked. For UK retail clients, FCA rules on leverage limits and negative balance protection apply to UK-authorised entities and may not apply to an offshore entity of the same brand." },
      { type: "h2", text: "If you have already sent money" },
      {
        type: "ul",
        items: [
          "Stop sending more. Recovery scams often follow, promising to get your money back for a fee.",
          "Keep records: messages, account statements, transaction references and website addresses.",
          "Contact your bank or card provider quickly. Depending on how you paid, there may be a route to dispute the payment.",
          "Report it to the relevant regulator and to the police or fraud reporting service in your country. In the UK that means Action Fraud and the FCA.",
        ],
      },
      { type: "h2", text: "Checking is quick, so do it every time" },
      { type: "p", text: "A check that takes ten minutes costs almost nothing compared with a deposit you cannot withdraw. verify.trading shows the regulator details and the source behind each verdict, so you can open the register and confirm it yourself." },
    ],
  },
  {
    slug: "fscs-cysec-and-client-money-protection-explained",
    title: "FSCS, CySEC ICF and client money protection explained",
    description:
      "What the FSCS and the CySEC Investor Compensation Fund actually cover, what segregated client money does, and why the legal entity holding your account matters.",
    date: "2026-09-29",
    category: "Broker safety",
    relatedPosts: ["how-to-check-if-a-broker-is-fca-regulated", "how-to-tell-a-scam-broker-from-a-real-one"],
    terms: ["fscs", "cysec-icf", "segregated-funds", "negative-balance-protection"],
    related: [
      { href: "/verify", label: "Verify a broker" },
      { href: "/glossary/fscs", label: "FSCS explained" },
      { href: "/compare/brokers", label: "Compare brokers" },
    ],
    body: [
      { type: "p", text: "When traders ask if a broker is safe, they usually mean two different things: will my money be protected if the broker fails, and can I lose more than I put in. Different rules answer each one, and none of them protects you from ordinary trading losses. This guide explains the main protections and how to check which ones apply to your account." },
      { type: "h2", text: "Three layers of protection" },
      { type: "h3", text: "1. Segregated client money" },
      { type: "p", text: "Regulated brokers in the UK must hold client money separately from their own funds under the FCA's client money rules. If the firm fails, client money is meant to be returned to clients rather than used to pay the firm's creditors. Segregation is a safeguard, not a guarantee: it depends on the firm's controls being followed, and it does not protect against trading losses." },
      { type: "h3", text: "2. Compensation schemes" },
      { type: "p", text: "If an authorised firm fails and cannot return client assets, a compensation scheme may pay eligible claims up to a limit. In the UK that is the Financial Services Compensation Scheme (FSCS), which at the time of writing covers up to 85,000 GBP per person per firm for investment claims. In Cyprus it is the Investor Compensation Fund (ICF) for clients of CySEC-licensed firms, which covers up to 20,000 euros per person." },
      { type: "callout", text: "Limits are reviewed and change. Check the scheme's own website for the current figure and for exactly what is covered before relying on it." },
      { type: "h3", text: "3. Negative balance protection" },
      { type: "p", text: "For retail clients of UK and EU-regulated CFD brokers, rules ensure you cannot lose more than the funds in your account on leveraged products. Professional clients and offshore entities may not get this, which is another reason to check which entity you are contracted with." },
      { type: "h2", text: "What compensation does not do" },
      {
        type: "ul",
        items: [
          "It does not cover trading losses or the fall in value of your positions.",
          "It does not cover you if the broker is unauthorised or is a scam. Compensation schemes cover authorised firms.",
          "It does not apply automatically to every entity in a broker group. It follows the entity that holds your account.",
          "It has limits per person, and different limits in different countries.",
        ],
      },
      { type: "h2", text: "Why the entity matters more than the brand" },
      { type: "p", text: "Large brokers commonly run separate companies in the UK, the EU, and in offshore jurisdictions. Each has its own regulator, its own leverage limits and its own compensation arrangements. If you sign up through a brand's global site, you may be onboarded to an offshore entity with weaker protection, sometimes with much higher leverage on offer. The legal name and licence number in the terms and conditions tell you which entity you are dealing with." },
      { type: "h2", text: "How to check your own account" },
      {
        type: "ol",
        items: [
          "Find the company name and licence number in your client agreement, not on a marketing page.",
          "Confirm that entity on its regulator's public register and check the permissions.",
          "Find out which compensation scheme covers it, if any, from the regulator or scheme website.",
          "Read the section of the agreement that says where client money is held and whether negative balance protection applies.",
          "If you are moved to a different entity later, treat it as a new decision and repeat the check.",
        ],
      },
      { type: "p", text: "Protection is one factor among several. It reduces the damage from a broker failure, but it does nothing about the risk in the trades themselves, which is why position sizing and drawdown limits matter just as much." },
    ],
  },
  {
    slug: "what-is-drawdown-and-how-to-manage-it",
    title: "What is drawdown and how to manage it",
    description:
      "Drawdown explained: how it is measured, why recovery needs bigger gains than the loss, how prop firms use daily and trailing limits, and practical ways to control it.",
    date: "2026-09-29",
    category: "Risk management",
    relatedPosts: ["position-sizing-how-much-to-risk-per-trade", "prop-firm-challenge-rules-that-catch-traders-out"],
    terms: ["drawdown", "maximum-drawdown", "daily-loss-limit", "trailing-drawdown", "balance-vs-equity"],
    related: [
      { href: "/prop-firm-traders", label: "For prop firm traders" },
      { href: "/journal", label: "Trading journal" },
      { href: "/glossary/drawdown", label: "Drawdown in the glossary" },
    ],
    body: [
      { type: "p", text: "Drawdown is the drop in your account from a high point to a later low. It is the number that tells you how much pain a strategy puts you through, and it is also the number prop firms use to decide when to close your account." },
      { type: "h2", text: "How drawdown is measured" },
      { type: "p", text: "Take the highest value your account reached, the peak, and the lowest value it fell to afterwards, the trough. The drawdown is the difference, usually shown as a percentage of the peak. An account that rises to 10,000 and then falls to 8,500 is in a 15% drawdown." },
      { type: "p", text: "Maximum drawdown is the largest such fall over a period. A strategy with a great total return can still have a maximum drawdown that most people could not stay disciplined through." },
      { type: "h2", text: "Why recovery is harder than the loss" },
      { type: "p", text: "A percentage loss needs a larger percentage gain to recover, because the gain is calculated on a smaller balance:" },
      {
        type: "ul",
        items: [
          "A 10% drawdown needs about 11.1% to recover.",
          "A 20% drawdown needs 25%.",
          "A 30% drawdown needs about 42.9%.",
          "A 50% drawdown needs 100%.",
        ],
      },
      { type: "p", text: "This asymmetry is the strongest argument for keeping single-trade risk small. A string of ordinary losses should dent the account, not break it." },
      { type: "h2", text: "Balance versus equity" },
      { type: "p", text: "Balance counts closed trades only. Equity also counts the floating profit or loss on open trades. Broker margin rules and many prop firm drawdown rules are measured on equity, so an open position that is deeply negative counts against you even before you close it. Always check which of the two a rule uses." },
      { type: "h2", text: "How prop firms use drawdown" },
      {
        type: "ul",
        items: [
          "Daily loss limit: the most the account may lose in one day. The definition of the day, and whether floating losses count, is set by the firm.",
          "Maximum drawdown: the overall loss the account may reach. It may be static, measured from the starting balance.",
          "Trailing drawdown: a limit that rises with your highest point, so your room to lose shrinks as you profit.",
        ],
      },
      { type: "p", text: "Rules differ between firms and change over time, so the only reliable source is the firm's own current rule text." },
      { type: "h2", text: "Ways to control drawdown" },
      {
        type: "ol",
        items: [
          "Fix a small risk per trade and size positions from the stop distance so every loss is the amount you planned.",
          "Set a daily stop: a loss at which you stop trading for the day, set well inside any firm limit.",
          "Watch correlated positions. Three trades on pairs that move together are close to one bigger trade.",
          "Reduce size, not just frequency, during a losing streak, and return to normal size only after a period of following your rules.",
          "Avoid the trades that create big single losses: averaging down, removing stops and doubling up after a loss.",
          "Track your drawdown from your journal so it is a measured number, not a feeling.",
        ],
      },
      { type: "callout", text: "This is general education, not advice. The right level of risk depends on your strategy, your finances and any rules you must follow." },
      { type: "h2", text: "Put a number on it" },
      { type: "p", text: "Decide before you start what drawdown would make you stop and re-examine your approach, and write it down. Having that line in advance is what stops a bad week becoming a blown account." },
    ],
  },
  {
    slug: "risk-reward-and-win-rate-what-the-maths-says",
    title: "Risk to reward and win rate: what the maths says",
    description:
      "How risk to reward ratio and win rate combine into expectancy, the break-even win rate at each ratio, and why a high ratio alone does not make a trade good.",
    date: "2026-09-29",
    category: "Risk management",
    relatedPosts: ["position-sizing-how-much-to-risk-per-trade", "what-is-drawdown-and-how-to-manage-it"],
    terms: ["risk-reward-ratio", "win-rate", "expectancy", "break-even"],
    related: [
      { href: "/tools/risk-reward-calculator", label: "Risk to reward calculator" },
      { href: "/journal", label: "Trading journal" },
      { href: "/glossary/expectancy", label: "Expectancy in the glossary" },
    ],
    body: [
      { type: "p", text: "Two numbers describe most of a strategy: how often it wins, and how much it makes on a win compared with what it loses on a loss. On their own each is misleading. Together they tell you whether the strategy can make money at all." },
      { type: "h2", text: "Risk to reward in one line" },
      { type: "p", text: "The ratio is the distance from entry to target divided by the distance from entry to stop. If you enter at 1.0850, put the stop at 1.0820 and the target at 1.0940, you risk 30 pips to make 90, a ratio of 1:3." },
      { type: "h2", text: "Win rate in one line" },
      { type: "p", text: "Win rate is the share of trades that close in profit. It says nothing about size. A strategy can win 70% of the time and lose money if its losers are much larger than its winners." },
      { type: "h2", text: "The break-even win rate" },
      { type: "p", text: "For any ratio, there is a win rate below which you lose money over many trades. It equals 1 divided by (1 plus the ratio), before costs:" },
      {
        type: "ul",
        items: [
          "1:1 needs to win 50% of trades.",
          "1:2 needs to win about 33%.",
          "1:3 needs to win 25%.",
          "1:0.5, risking two to make one, needs to win about 67%.",
        ],
      },
      { type: "p", text: "Spreads, commissions and slippage push each of these up, so the real break-even is higher. On short-term trades with tight stops the cost drag can be a large share of the gross result." },
      { type: "h2", text: "Expectancy: putting both together" },
      { type: "p", text: "Expectancy is the average result per trade: the win rate times the average win, minus the loss rate times the average loss. With a 40% win rate, an average win of 300 and an average loss of 100, expectancy is (0.4 times 300) minus (0.6 times 100) = 60 per trade, before costs." },
      { type: "p", text: "A positive expectancy is necessary, not sufficient. It is estimated from past trades, so it is only as reliable as the sample behind it, and it can change when market conditions change." },
      { type: "h2", text: "Why a high ratio is not a free lunch" },
      { type: "p", text: "It is easy to draw a target far away and call the trade 1:5. But a distant target is reached less often, so the win rate falls as the ratio rises. Good targets sit at levels where price has a reason to pause, such as prior highs and lows, not at whatever number makes the ratio look attractive." },
      { type: "h2", text: "Use it before, and after, the trade" },
      {
        type: "ol",
        items: [
          "Before entering, calculate the ratio from the actual stop and target, including the spread.",
          "Skip trades whose ratio does not clear your own minimum, whatever that is for your strategy.",
          "After enough trades, calculate your real win rate and average win and loss from your journal.",
          "Compare your real expectancy with what you assumed. If they differ, fix the assumption, not the maths.",
        ],
      },
      { type: "callout", text: "None of this predicts the next trade. It tells you whether the arithmetic of your approach can work, which is the minimum you should know before risking money. This is education, not advice." },
    ],
  },
  {
    slug: "how-to-keep-a-trading-journal",
    title: "How to keep a trading journal that you will actually use",
    description:
      "What to record, how often to review, and how to turn a trading journal into a record of your habits, with a simple template for each session.",
    date: "2026-09-29",
    category: "Trading psychology",
    relatedPosts: ["revenge-trading-and-tilt-how-to-stop", "what-is-drawdown-and-how-to-manage-it"],
    terms: ["trading-journal", "overtrading", "win-rate", "expectancy"],
    related: [
      { href: "/journal", label: "Trading journal" },
      { href: "/mind", label: "Mind: trading psychology" },
      { href: "/glossary/trading-journal", label: "Trading journal in the glossary" },
    ],
    body: [
      { type: "p", text: "Most traders know they should keep a journal and most stop within a few weeks. The usual reason is that the journal is too heavy: too many fields, too much writing, and no clear payoff. A good journal is small enough to complete on a bad day, which is exactly when it is most useful." },
      { type: "h2", text: "What a journal is for" },
      { type: "p", text: "Memory edits. We remember the big win and the trade that felt unlucky, and we forget the ten small rule breaks between them. A written record shows what you did, not what you recall doing, and lets you look for patterns across weeks." },
      { type: "h2", text: "The minimum useful entry" },
      {
        type: "ul",
        items: [
          "The result of the session: profit or loss, in money or in R (multiples of your planned risk).",
          "Whether you followed your plan: yes, partly or no.",
          "Your mood before and after, in a word or a simple scale.",
          "One line on the lesson: the thing to repeat or the thing to stop.",
        ],
      },
      { type: "p", text: "That takes a minute. Add trade-level details, such as the instrument, size, entry, stop and target, when you have the habit. If your broker data can be imported, let it fill those in so you only write the human part." },
      { type: "h2", text: "What to review, and when" },
      { type: "h3", text: "Weekly" },
      { type: "p", text: "Read the week's entries in one sitting. Count how many sessions followed the plan, how many trades broke the rules and what was happening when they did: time of day, after a loss, when tired. One or two patterns are enough to act on." },
      { type: "h3", text: "Monthly" },
      { type: "p", text: "Calculate your win rate, average win, average loss and drawdown for the month. Compare the numbers with what you assumed when you sized your trades." },
      { type: "h2", text: "Patterns worth looking for" },
      {
        type: "ul",
        items: [
          "Trades taken after a loss versus after a win, and how their size compares.",
          "Results by time of day and by day of the week.",
          "Sessions with poor sleep or high stress against your usual results.",
          "Trades where the stop was moved, removed or widened.",
          "The number of trades per day on your best and worst days.",
        ],
      },
      { type: "h2", text: "For prop firm challenges" },
      { type: "p", text: "A challenge has a target, a set of limits and often a minimum number of trading days. Track your cumulative profit against the target and your drawdown against the daily and overall limits every day, so you know your remaining room before you place a trade, not after." },
      { type: "h2", text: "Habits that make it stick" },
      {
        type: "ol",
        items: [
          "Attach it to something you already do, such as closing the platform for the day.",
          "Keep the daily entry to a minute, and save the deeper review for the weekend.",
          "Record the bad days first. Skipping them is how a journal becomes flattering fiction.",
          "Write what you would do differently, not only what happened.",
          "Do not judge yourself in the entry. Its purpose is accurate data.",
        ],
      },
      { type: "callout", text: "A journal records; it does not advise. Use it to see your own behaviour clearly, then change one thing at a time." },
    ],
  },
  {
    slug: "revenge-trading-and-tilt-how-to-stop",
    title: "Revenge trading and tilt: how to stop",
    description:
      "What revenge trading and tilt look like, the triggers behind them, and a set of rules and routines that interrupt the pattern before it costs you an account.",
    date: "2026-09-29",
    category: "Trading psychology",
    relatedPosts: ["how-to-keep-a-trading-journal", "what-is-drawdown-and-how-to-manage-it"],
    terms: ["revenge-trading", "tilt", "overtrading", "fomo"],
    related: [
      { href: "/mind", label: "Mind: trading psychology" },
      { href: "/journal", label: "Trading journal" },
      { href: "/glossary/revenge-trading", label: "Revenge trading in the glossary" },
    ],
    body: [
      { type: "p", text: "You take a loss you thought was unfair. Within minutes you have opened another trade, bigger than usual, with no clear setup, because you want the money back. That is revenge trading, and it is one of the most common ways a good week becomes a bad month." },
      { type: "h2", text: "What it looks like" },
      {
        type: "ul",
        items: [
          "Trading faster after a loss, with less time between entries.",
          "Increasing size to recover the loss in a single trade.",
          "Taking setups you would normally skip, or having no setup at all.",
          "Removing or widening a stop so the trade is allowed to keep losing.",
          "Feeling you cannot stop until you are back to even.",
        ],
      },
      { type: "p", text: "Tilt is the wider state: any emotional condition, such as frustration, boredom, fear or overconfidence, in which your plan stops governing your trading. Revenge trading is tilt with a target." },
      { type: "h2", text: "Why it happens" },
      { type: "p", text: "A loss registers as something taken from you, and the instinct is to take it back. The more your income or self-image depends on trading, the stronger the pull. Pressure from a prop firm rule, a limit that is close, or money you cannot afford to lose all make it worse." },
      { type: "h2", text: "The triggers to know" },
      {
        type: "ul",
        items: [
          "A stop-out that was followed by price going your way.",
          "A run of losses, or one large loss.",
          "Being close to a daily loss limit or a profit target.",
          "Poor sleep, stress or trading while distracted.",
          "A missed move, which leads to chasing.",
        ],
      },
      { type: "h2", text: "Rules that interrupt the pattern" },
      { type: "p", text: "Willpower fails in the moment, so decide the rules in advance and make them automatic." },
      {
        type: "ol",
        items: [
          "A daily loss stop. Pick a loss, in money or as a percentage, at which you stop for the day, and place it inside any firm limit.",
          "A consecutive-loss rule. After two or three losses in a row, take a set break away from the screen.",
          "A cooling-off period. After any stop-out, wait a fixed time, such as 15 minutes, before the next entry.",
          "Fixed size. Position size comes from your plan and does not change after a loss.",
          "A daily trade limit. Once it is reached, you are done.",
          "A written plan before the session, so that every trade has to match something you decided when calm.",
        ],
      },
      { type: "h2", text: "Notice it early" },
      { type: "p", text: "Before you enter a trade, ask three questions: is this in my plan, is the size normal, and how do I feel? If the answer to the first two is no, or if you feel angry or desperate, close the platform. Noticing your state before entering is a skill and it improves with practice." },
      { type: "h2", text: "Use your records" },
      { type: "p", text: "A journal that records mood next to results shows whether your worst trades cluster after losses, late in the day or when tired. Once the pattern is visible, a rule can target it. Self-assessments, such as the one in Mind, can also point at which habits, such as fear, chasing or process, are your weakest." },
      { type: "callout", text: "Trading can affect wellbeing. If it is causing you real distress or harm, speak to a qualified professional or a support service. This article is general education and not medical or investment advice." },
    ],
  },
  {
    slug: "how-to-trade-around-economic-news",
    title: "How to trade around economic news",
    description:
      "Which economic releases move markets, what happens to spreads and stops around them, and how to plan a session and follow a prop firm news rule using a calendar.",
    date: "2026-09-29",
    category: "Markets and news",
    relatedPosts: ["prop-firm-challenge-rules-that-catch-traders-out", "position-sizing-how-much-to-risk-per-trade"],
    terms: ["red-folder-news", "non-farm-payrolls", "cpi", "news-trading-rule", "slippage", "spread"],
    related: [
      { href: "/economic-calendar", label: "Economic calendar" },
      { href: "/intelligence", label: "Daily market brief" },
      { href: "/glossary/red-folder-news", label: "Red-folder news in the glossary" },
    ],
    body: [
      { type: "p", text: "Scheduled data releases are the most predictable source of volatility in the market. You do not know what the number will be, but you know exactly when it lands, which lets you plan for it. Whether you want to trade the event, avoid it, or simply not be caught by it, the first step is the same: know when it is." },
      { type: "h2", text: "The releases that matter most" },
      {
        type: "ul",
        items: [
          "Central bank interest rate decisions and the accompanying statements and press conferences.",
          "Inflation reports, such as the consumer price index (CPI).",
          "Employment data, including the US non-farm payrolls report, usually released on the first Friday of the month.",
          "Growth data such as GDP, and business surveys such as purchasing managers' indexes.",
          "Retail sales and other consumer data.",
        ],
      },
      { type: "p", text: "Calendars label events by expected impact, and the high-impact ones are often marked in red, which is where the term red-folder news comes from. Which events matter for you depends on what you trade: the US dollar, gold and indices react most to US data, while a currency reacts most to its own economy's releases." },
      { type: "h2", text: "What happens to the market around a release" },
      {
        type: "ul",
        items: [
          "Spreads widen because liquidity providers pull back, so entries and exits cost more.",
          "Price can jump past stop levels, so a stop may fill at a worse price than you set. This is slippage.",
          "Moves can reverse sharply as the market digests the figure, and the first reaction is not always the lasting one.",
          "Volatility can stay elevated for a while after the release, not just a few seconds.",
        ],
      },
      { type: "h2", text: "Forecast, previous and actual" },
      { type: "p", text: "Markets react to the difference between the actual figure and the consensus forecast, not to the figure itself. A strong number that was expected can leave price flat, while a modest surprise can move it a lot. Forecasts are estimates and can be wrong, and figures can be revised afterwards." },
      { type: "h2", text: "Three ways to handle it" },
      { type: "h3", text: "Stay flat" },
      { type: "p", text: "Close positions or do not open new ones before the event and re-engage after volatility settles. It is the simplest approach and the only one that removes the risk entirely." },
      { type: "h3", text: "Reduce size" },
      { type: "p", text: "Keep a position but cut its size and check where the stop is, allowing for slippage in your risk calculation." },
      { type: "h3", text: "Trade the event deliberately" },
      { type: "p", text: "Some traders specialise in news. It demands a plan for the wider spread, the slippage and the reversal risk, and it is not a good fit for a small account or a strict drawdown limit." },
      { type: "h2", text: "News rules at prop firms" },
      { type: "p", text: "Some prop firms restrict trading, or holding positions, for a window around high-impact events, and the consequences of a breach vary by firm. The window, the events covered and the penalty are all in the firm's rules. Use the calendar to see when events fall, then read the exact rule. Do not rely on a summary or on what another trader said." },
      { type: "h2", text: "A simple weekly routine" },
      {
        type: "ol",
        items: [
          "At the start of the week, list the high-impact events for the currencies and assets you trade.",
          "Put them in your session plan with times converted to your own time zone.",
          "Decide in advance for each one whether you will stay flat, reduce size or trade it.",
          "Check the time zone on the calendar. Errors here are common and expensive.",
          "After the event, record what happened to spread and price in your journal.",
        ],
      },
      { type: "callout", text: "A calendar tells you when volatility is likely. It does not tell you which way price will go. This is general education, not a trade recommendation." },
    ],
  },
];
